### ISSUE TITLE
Windows 8.1:  Can't load IA 32-bit .dll

### ISSUE THREAD

**Issue by malafeev** [kwhat/jnativehook#119]
Issue on Windows 8.1, java version "1.8.0_45” :

Exception in thread "JavaFX Application Thread" java.lang.UnsatisfiedLinkError:
C:\Users\User\AppData\Local\Temp\JNativeHook-2.0.3.dll: Can't load IA 32-bit .dl
l on a AMD 64-bit platform
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(Unknown Source)
        at java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.lang.Runtime.load0(Unknown Source)
        at java.lang.System.load(Unknown Source)
        at org.jnativehook.GlobalScreen.(Unknown Source)

**Comment by kwhat** [comment]
For some reason it's auto detecting the wrong platform.  As long as you didn't change the default library locator, the DLL bit width should be loaded from System.getProperty("os.arch").  Let me know what your version of java is claiming for that property.

**Comment by malafeev** [comment]
1.8.0_45

**Comment by kwhat** [comment]
System.getProperty("os.arch") not the JVM version.

**Comment by kwhat** [comment]
Any status on the output of System.getProperty("os.arch")?  For some reason it thinks your a 32-bit jvm but really your a 64-bit jvm.  Please update or close.

**Comment by malafeev** [comment]
yes, looks so. 32-bit jvm on 64-bit Windows

**Comment by kwhat** [comment]
32-bit jvm on 64 bit widows does work, for some reason System.getProperty("os.arch") is returning the wrong value.  1.8.0_45 is the jvm version not the architecture.
