### ISSUE TITLE
Problem building,  " Cannot run program sh " ...

### ISSUE THREAD

**Issue by ingAntonioAcosta** [kwhat/jnativehook#122]
...
download-libuiohook:
     [echo] Downloading libUIOHook source...
      [get] Getting: https://github.com/kwhat/libuiohook/archive/1.0.zip
      [get] To: C:\Users\Gaming\Documents\NetBeansProjects\libreriaNativeHook\test13\jnativehook-2.0.3\bin\libuiohook-1.0.zip
      [get] https://github.com/kwhat/libuiohook/archive/1.0.zip moved to https://codeload.github.com/kwhat/libuiohook/zip/1.0
      [get] ....................................................
      [get] ...................................................
    [unzip] Expanding: C:\Users\Gaming\Documents\NetBeansProjects\libreriaNativeHook\test13\jnativehook-2.0.3\bin\libuiohook-1.0.zip into C:\Users\Gaming\Documents\NetBeansProjects\libreriaNativeHook\test13\jnativehook-2.0.3\src\libuiohook

bootstrap-libuiohook:
     [echo] Bootstrapping libUIOHook...
[autoreconf] autoreconf --verbose --force --install

BUILD FAILED
C:\Users\Gaming\Documents\NetBeansProjects\libreriaNativeHook\test13\jnativehook-2.0.3\build.xml:351: Execute failed: java.io.IOException: Cannot run program "sh" (in directory "C:\Users\Gaming\Documents\NetBeansProjects\libreriaNativeHook\test13\jnativehook-2.0.3\src\libuiohook"): CreateProcess error=2, El sistema no puede encontrar el archivo especificado
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at java.lang.Runtime.exec(Runtime.java:620)
        at org.apache.tools.ant.taskdefs.launcher.Java13CommandLauncher.exec(Java13CommandLauncher.java:58)
        at org.apache.tools.ant.taskdefs.Execute.launch(Execute.java:426)
        at org.apache.tools.ant.taskdefs.Execute.execute(Execute.java:440)
        at org.apache.tools.ant.taskdefs.ExecTask.runExecute(ExecTask.java:629)
        at org.apache.tools.ant.taskdefs.ExecTask.runExec(ExecTask.java:670)
        at org.apache.tools.ant.taskdefs.ExecTask.execute(ExecTask.java:496)
        at org.jnitasks.autotools.AutoreconfTask.execute(AutoreconfTask.java:113)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:435)
        at org.apache.tools.ant.Target.performTasks(Target.java:456)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
        at org.apache.tools.ant.Main.runBuild(Main.java:854)
        at org.apache.tools.ant.Main.startAnt(Main.java:236)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:285)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:112)
Caused by: java.io.IOException: CreateProcess error=2, El sistema no puede encontrar el archivo especificado
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
        at java.lang.ProcessImpl.start(ProcessImpl.java:137)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 24 more

Total time: 3 seconds

i tried to many times to build from the source, but this error keps showing up.

**Comment by kwhat** [comment]
You are not building from the MinGW shell.  Run ant from the MinGW shell and it should work. See the wiki for instructions on compiling from src.
