### ISSUE TITLE
Used to work fine then got UnsatifiedLinkError on LXDE

### ISSUE THREAD

**Issue by abc123me** [kwhat/jnativehook#145]
I have tried restarting, and running as superuser, I did re-download it and it seems the older version works not the one I have now
This is NOT my code, It failed when using the demo, last time I used it there were no problems at all now I get this:
Exception in thread "AWT-EventQueue-0" java.lang.UnsatisfiedLinkError: /tmp/libJNativeHook-2.1.0.x86_64.so: libxkbcommon-x11.so.0: cannot open shared object file: No such file or directory
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at org.jnativehook.GlobalScreen.<clinit>(Unknown Source)
	at org.jnativehook.example.NativeHookDemo.<init>(Unknown Source)
	at org.jnativehook.example.NativeHookDemo$1.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by kwhat** [comment]
Hi, 2.1 requires lib XKB common.  I think I forgot to update the readme before the release, however the trunk should be up to date.

**Comment by abc123me** [comment]
Could you include how to install lib xkb common in the readme, anyways thanks!

**Comment by kwhat** [comment]
It should be listed on the 2.1 read me file.  I have also updated the build instructions to the wiki.  Sorry for the inconvenience, 2.1.1 will be up to date ;)
