### ISSUE TITLE
UnsatisfiedLinkError when run on raspberry pi 4

### ISSUE THREAD

**Issue by Sapu98** [kwhat/jnativehook#275]
Hi, I've made a small program using the latest jnativehook lib, it works fine on both Windows and Mac, but if I try to run it on Raspbian I get this error:

Exception in thread "main" java.lang.UnsatisfiedLinkError: org.jnativehook.GlobalScreen.getAutoRepeatRate()Ljava/lang/Integer;
	at org.jnativehook.GlobalScreen.getAutoRepeatRate(Native Method)
	at org.jnativehook.GlobalScreen.<clinit>(Unknown Source)
	at me.Main.main(Main.java:20)

This in my main class and it causes the exception:  

(MouseListener is a class that implements NativeMouseInputListener)
line 19: MouseListener globalMouseListener = new MouseListener();
line 20: GlobalScreen.addNativeMouseListener(globalMouseListener);

**Comment by Sapu98** [comment]
Found the solution: in the program jar, in org->jnativehook->lib->linux-> rename "arm6" to "arm"
