### ISSUE TITLE
native library JNativeHook.dll

### ISSUE THREAD

**Issue by hennyC** [kwhat/jnativehook#32]
How can I solve this ?

run:
Dec 17, 2014 9:06:40 PM org.jnativehook.GlobalScreen loadNativeLibrary
SEVERE: Unable to extract the native library /org/jnativehook/lib/windows/x86_64/JNativeHook.dll!

Exception in thread "main" java.lang.UnsatisfiedLinkError
    at org.jnativehook.GlobalScreen.loadNativeLibrary(GlobalScreen.java:714)
    at org.jnativehook.GlobalScreen.<init>(GlobalScreen.java:88)
    at org.jnativehook.GlobalScreen.<clinit>(GlobalScreen.java:64)
    at keylogger.KeyLogger.main(KeyLogger.java:35)
Java Result: 1
BUILD SUCCESSFUL (total time: 0 seconds)

**Comment by kwhat** [comment]
@hoat23 There are detailed instructions in the WIKI for the project.  I am working on a packer script to help make this process easier.

**Comment by avialaynen** [comment]
> There are detailed instructions in the WIKI for the project

And where can I find this wiki? Google is silent.
