### ISSUE TITLE
Jnative hook crashes on mac os

### ISSUE THREAD

**Issue by dipeshji** [kwhat/jnativehook#359]
Jnative hook crashes on mac os after 2hr or some times after one day. Crashing Interval is not fixed.
Attached crash logs for your reference.
[error.txt](https://github.com/kwhat/jnativehook/files/6936208/error.txt)

**Comment by kwhat** [comment]
Please test with 2.2.0.  I am not sure what could be causing this and it will be difficult to fix if I cannot reliably reproduce it.

**Comment by dipeshji** [comment]
You can refer the error.txt file i have attached in first comment. And is 2.2.0 is present on maven central?

**Comment by kwhat** [comment]
> You can refer the error.txt file i have attached in first comment

Yah, I have looked at it but it only tells me roughly where it is crashing but not why.  If I can't reproduce the problem, I have no idea if anything I change fixes it.

> And is 2.2.0 is present on maven central?

It should be on maven central but probably doesn't fix this issue.  There is a branch were some of these fixes were tried, but I have no idea if they worked: https://github.com/kwhat/libuiohook/tree/mac_fixes

**Comment by dipeshji** [comment]
Also it hangs the latest ubuntu 21. Can you please suggest me a way for mac to work. If need any extra reports i can provide.

**Comment by avrilmaomao** [comment]
2.2.0 works fine but failed to load native libraries when running with fat jars. 

When I switched to 2.2-snapshot , the crashing problem happens again.Crashes everytime when Capslock was pressed.

**Comment by kwhat** [comment]
> 2.2.0 works fine but failed to load native libraries when running with fat jars.

It is never going to work with a fat jar unless you write your own loader.

**Comment by kwhat** [comment]
> When I switched to 2.2-snapshot , the crashing problem happens again.Crashes everytime when Capslock was pressed.

I can duplicate the problem so ill see if I can figure out a fix.

**Comment by avrilmaomao** [comment]
> > 2.2.0 works fine but failed to load native libraries when running with fat jars.
> 
> It is never going to work with a fat jar unless you write your own loader.

Got it, Thanks. I'll put dependencies to a separate folder . 

I'll continue to figure out how to reproduce the crashing problem.  It didn't crash when running from my IDE, but crashes when running as an app packaged by [JPackage](https://docs.oracle.com/en/java/javase/17/docs/specs/man/jpackage.html).

**Comment by kwhat** [comment]
The problem is somewhere with [this method](https://github.com/kwhat/libuiohook/blob/1.2/src/darwin/input_hook.c#L584), probably the objc_ functions.  I have no idea why it isn't working.

**Comment by avrilmaomao** [comment]
Using _Java 16_'s Jpackage command instead of _Java 17_ solved the crashing problem.
Seems complicated. 
Maybe add an option to  ignore  **Caps Lock** and other system keys?

**Comment by kwhat** [comment]
It has to be some kind of thread safety issue with objc_sendMsg but I still have no idea why.  I am likely going to just disable objc and go back to some hacks i was using before implementing that.

**Comment by avrilmaomao** [comment]
> It has to be some kind of thread safety issue with objc_sendMsg but I still have no idea why. I am likely going to just disable objc and go back to some hacks i was using before implementing that.

If any snapshots version is available, I'll be happy to give it a try.

**Comment by kwhat** [comment]
I have some time tomorrow to work on it.

**Comment by kwhat** [comment]
I have found a solution but it is going to take some time to implement.

**Comment by avrilmaomao** [comment]
> I have found a solution but it is going to take some time to implement.

Take your time 💪.   
There are some workarounds I can use for that crash.  Not sure @dipeshji sovled his or not.

**Comment by dipeshji** [comment]
@avrilmaomao unable to resolve the problem, it crashes on mac OS and hangs Ubuntu 21.4 and the 2.2 version doesn't loads. If you have any feasible work around please do help me on this.

**Comment by kwhat** [comment]
I still cannot duplicate the Ubuntu deadlock but this should solve a crash on OS X.  It is very unlikely that this library is causing a freeze on Linux, I suspect something else is going on.

**Comment by avrilmaomao** [comment]
> @avrilmaomao unable to resolve the problem, it crashes on mac OS and hangs Ubuntu 21.4 and the 2.2 version doesn't loads. If you have any feasible work around please do help me on this.

In your log , I saw you also packaged you code into an Mac app.  Which java version and packaging tool are you using?

**Comment by kwhat** [comment]
The OSX fix has been released.  Please test the Linux bug again, I have released a fix for a linux bug, just not the bug you described.

**Comment by avrilmaomao** [comment]
Using 2.2.1 from Maven central and Java 17, the crashing does not appear. 
Thanks for your work.

**Comment by dipeshji** [comment]
@avrilmaomao i'm using java 8 and for packaging i am using io.github.fvarrui.

**Comment by avrilmaomao** [comment]
> @avrilmaomao i'm using java 8 and for packaging i am using io.github.fvarrui.

You can try jnativehook 2.2.1 now to see if it's still crashing.

**Comment by dipeshji** [comment]
@avrilmaomao for sure i will try this

**Comment by dipeshji** [comment]
@avrilmaomao this is an another problem with 2.2.1 "SEVERE: /opt/timesheet/libs/libJNativeHook.so (Permission denied)
Exception in thread "main" java.lang.UnsatisfiedLinkError: /opt/timesheet/libs/libJNativeHook.so (Permission denied)
    at com.github.kwhat.jnativehook.GlobalScreen.<clinit>(GlobalScreen.java:91)
    at com.fourtysevenbillion.timesheet.Timesheet.main(Timesheet.java:39)" do you have any solution to this?

**Comment by kwhat** [comment]
> and for packaging i am using io.github.fvarrui.

How exactly does this work, particularly with dependencies like this library?  Is it creating a fat jar where all dependencies are extracted and rolled into the jar?  

If that is the case, it would be totally unsupported and highly unlikely to work out of the box.  You can make it work if you need to, but you would have to do your own library loading either by specifying java.library.path or by creating a custom implementation of [NativeLibraryLocator](https://github.com/kwhat/jnativehook/blob/2.2/src/main/java/com/github/kwhat/jnativehook/NativeLibraryLocator.java) for your situation.  You can take a look at the [DefaultLibraryLocator](https://github.com/kwhat/jnativehook/blob/2.2/src/main/java/com/github/kwhat/jnativehook/DefaultLibraryLocator.java) for an example of how to implement it.

> this is an another problem with 2.2.1 "SEVERE: /opt/timesheet/libs/libJNativeHook.so (Permission denied)

That library name should be different for 2.2.1, that looks like 2.2.0.  If you are going to have the jar in a read-only location, you probably want to pre-extract it from the jar before putting it in the read-only location.  All the native libraries are in the resources com/github/kwhat/jnativehook/lib folder.  File names should be something like `libJNativeHook-2.2.1.x86_64.so`.
