### ISSUE TITLE
URI is not hierarchical

### ISSUE THREAD

**Issue by thewen99** [kwhat/jnativehook#448]
It worked fine when I ran the project with the IDE, but it didn't work when I ran it with the JAR

`2023-08-14 21:18:59.159 ERROR 10375 --- [           main] com.github.kwhat.jnativehook             : URI is not hierarchical
2023-08-14 21:18:59.163  INFO 10375 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2023-08-14 21:18:59.192 ERROR 10375 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.UnsatisfiedLinkError: URI is not hierarchical
	at com.github.kwhat.jnativehook.GlobalScreen.<clinit>(GlobalScreen.java:91) ~[jnativehook-2.2.1.jar!/:2.2.1]
	at com.sinstry.station.service.CardRunner.run(CardRunner.java:23) ~[classes!/:1.0.0-SNAPSHOT]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:810) [spring-boot-2.4.5.jar!/:2.4.5]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:800) [spring-boot-2.4.5.jar!/:2.4.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:346) [spring-boot-2.4.5.jar!/:2.4.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1340) [spring-boot-2.4.5.jar!/:2.4.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1329) [spring-boot-2.4.5.jar!/:2.4.5]
	at com.sinstry.station.StationMsApplication.main(StationMsApplication.java:26) [classes!/:1.0.0-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_312]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_312]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_312]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_312]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) [sinstry-station-mes-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) [sinstry-station-mes-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) [sinstry-station-mes-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) [sinstry-station-mes-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]`

**Comment by ZaleJ** [comment]
@thewen99 Bro, I got the same problem. How did you solved it?

**Comment by thewen99** [comment]
> [@thewen99](https://github.com/thewen99) Bro, I got the same problem. How did you solved it?

https://github.com/kwhat/jnativehook/issues/428
你试试这个里面的方法
