### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by gblogbd** [kwhat/jnativehook#85]
sorry for my poor english 
BUT thanks for the source code 
i'm reading the source code about JNI now
thanks again 

i want to builid a project about mouse‘s distance base on jnativehook

**Comment by gblogbd** [comment]
it's very complex to complie the jnativehook 
would you  transfer me the win X64 dll 、win X86 dll and jnativehook jar please？

**Comment by gblogbd** [comment]
BUILD FAILED
C:\Users\Yz\Desktop\jnativehook-master\build.xml:173: Could not load definitions
 from resource org/jnitasks/antlib.xml. It could not be found.

how to fix it ?

**Comment by gblogbd** [comment]
bootstrap-libuiohook:
     [echo] Bootstrapping libUIOHook...
[autoreconf] autoreconf --verbose --force --install

BUILD FAILED
C:\Users\Yz\Desktop\jnativehook-master\build.xml:351: Execute failed: java.io.IO
Exception: Cannot run program "sh" (in directory "C:\Users\Yz\Desktop\jnativehoo
k-master\src\libuiohook"): CreateProcess error=2, 系统找不到指定的文件。
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at java.lang.Runtime.exec(Runtime.java:620)
        at org.apache.tools.ant.taskdefs.launcher.Java13CommandLauncher.exec(Jav
a13CommandLauncher.java:58)
        at org.apache.tools.ant.taskdefs.Execute.launch(Execute.java:428)
        at org.apache.tools.ant.taskdefs.Execute.execute(Execute.java:442)
        at org.apache.tools.ant.taskdefs.ExecTask.runExecute(ExecTask.java:629)
        at org.apache.tools.ant.taskdefs.ExecTask.runExec(ExecTask.java:670)
        at org.apache.tools.ant.taskdefs.ExecTask.execute(ExecTask.java:496)
        at org.jnitasks.autotools.AutoreconfTask.execute(AutoreconfTask.java:113
)

how to fix this problem?

**Comment by kwhat** [comment]
Hi,

Because JNativeHook uses JNI, you must have a C99 GCC compatible compiler installed.  There are instructions for setting up your system with MinGW [here](https://github.com/kwhat/jnativehook/blob/master/wiki/Compiling.md#windows).  You can allegedly use the new version of Visual Studio to compile, however, it is not currently supported.
